Documentation Improvements
criticalmanufacturing/generator-html pull request #5
Opened 2017-05-09 13:39 UTC by freddykrunn

2017-05-09 13:42 UTC, jpsfs requested changes

2017-05-09 13:42 UTC, jpsfs commented on generators/widget/templates/widgetSettings.ts
> + * Please provide a meaningful description of this Widget Settings and what it is needed for, adn describe all the properties that are configurable in the correspondent Widget
Small typo on "adn"

2017-05-09 13:51 UTC, francisco-maciel requested changes

2017-05-09 13:51 UTC, francisco-maciel commented on generators/component/templates/component.ts
> + * * How it behaves with different sizes?
Change to _"How does it behave with different sizes?"_

2017-05-09 13:51 UTC, francisco-maciel commented on generators/widget/templates/widget.ts
>   * * How it behave with different sizes?
Change to _"How does it behave with different sizes?"_

2017-05-09 13:51 UTC, francisco-maciel commented on generators/dataSource/templates/dataSource.ts
> + * * How it behave with different sizes?
I don't think a data source has _"sizes"_, i think you should remove this line.

2017-05-09 14:23 UTC, jpsfs approved these changes

2017-05-11 11:14 UTC, francisco-maciel approved these changes

2017-05-11 11:15 UTC, merged